modLoader="javafml"
loaderVersion="[1,)"
license="Apache-2.0"
issueTrackerURL="https://github.com/xhyrom/notchs-versioning/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="xhyrom"
description='''${mod_description}'''
logoFile="icon.png"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1.217,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21.11,]"
ordering="NONE"
side="BOTH"